### ISSUE TITLE
Send email about student community dinner

### ISSUE THREAD

**Issue by linamoon** [uxutdallas/ARCHIVE-communitydinner-feb2016#3]
After restaurant is reserved.

**Comment by 01parkelly** [comment]
Restaurant reserved.

Thursday, 2/18 at 6:30 pm.
Blue Mesa (Addison)
14866 Montfort Dr, Dallas, TX 75254
http://www.bluemesagrill.com/

**Comment by linamoon** [comment]
Thankies @angelakou for sending out emails - let's send out a reminder email this Wednesday so people remember.
